development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: risflecting_development
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test: &test
  adapter: postgresql
  encoding: unicode
  database: risflecting_test
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

cucumber:
  <<: *test